version: '3'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./code:/var/www/app
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - fpm-network
    php:
        image: php:fpm
        volumes:
            - ./code:/var/www/app
        networks:
            - fpm-network

networks:
    fpm-network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 10.80.0.0/16
